server:
  port: 8070
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_mem
    username: sa
    password: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
